### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by kahowell** [egineering-llc/collectd-fast-jmx#15]
Hard to justify use in most environments without a license.

Can you please add a license file to the root of the project?

**Comment by bvarner** [comment]
@tkelley-eg Any suggestions on a preferred license? The version of commons-math this uses is APL 2.0, so we should be able to use just about anything.

**Comment by tkelley-eg** [comment]
I’m good with APL 2.0.


Troy J. Kelley
E-gineering, LLC
8415 Allison Pointe Blvd | Suite 200
Indianapolis, IN | 46250 | 317.348.1780
www.e-gineering.com<http://www.e-gineering.com/>

**Comment by bvarner** [comment]
LISCENSE.txt added to master.
