### ISSUE TITLE
JBoss: Failed to collect JVM statistics

### ISSUE THREAD

**Issue by tux21b** [egineering-llc/collectd-fast-jmx#16]
This bug might be related to https://github.com/egineering-llc/collectd-fast-jmx/issues/6, also with JBoss 4.2:

Once we tell JBoss to use the platform mbean server (setting `JAVA_OPTS="$JAVA_OPTS -Djboss.platform.mbeanserver Djavax.management.builder.initial=org.jboss.system.server.jmx.MBeanServerBuilderImpl"`) FastJMX fails to collect basic JVM statistics, printing the following error messages:

    [2015-07-09 18:49:36] FastJMX Plugin: Failed to collect: java.lang:type=MemoryPool,name=PS Survivor  Space@service:jmx:rmi:///jndi/rmi://127.0.0.1:8855/jmxrmi InstanceNotFound consecutive count=5

(and similar messages for the GC stats).

As soon as we connect via the JConsole to view the MBean, everything starts to work and FastJMX is able to collect the stats as expected.

Was anyone able to get this setup working? We would like to collect JVM and JBoss stats. Many thanks!

**Comment by bvarner** [comment]
I haven’t tried it on 4.2.

I have run with JBoss EAP 6.x, and 5.x.

Thanks for the report, as I have availability I’ll look into it.

-Bryan

**Comment by tux21b** [comment]
Wow, many thanks for responding so quickly. Feel free to ask for any additional information if required.

**Comment by bvarner** [comment]
Well, I'm currently tasked to a few other projects, but when I have the time (or if I get bored at home) I'll stand up a 4.2 instance and see if I can figure out the issue.

**Comment by tux21b** [comment]
I think that's the bug we are experiencing:

> Problems accessing MXBeans on JBoss
> 
> Another strange bug, which is not related to JSR-160 but present in JBoss 4.2.3 and 5.1, is,   that MXBeans (those in the JMX domain java.lang) are invisible until their meta data is fetched via mBeanServer.getMBeanInfo(). Accessing such a MBean without at least one prior fetch of the MBeanInfo metadata results in an ObjectInstanceNotFoundException. The workaround for jmx4perl is to transparently fetch the MBeanInfo when a MXBean on JBoss is requested. For now, this works in the agent-mode but not yet in the proxy mode.

Source: https://labs.consol.de/de/jmx4perl/2009/11/23/jboss-remote-jmx.html

**Comment by bvarner** [comment]
Ah Hah!

That sounds like something I could fix pretty quickly. Thanks for tracking this down.

Of course, if you wanted to fork & do your on Pull Request — We’d love to help you help yourself. :-)

**Comment by NitzKish** [comment]
Can u plz tell me what information can we fetch from JBoss AS JVM. If possible plz provide me the links of those.

**Comment by bvarner** [comment]
@tux21b, care to build off the branch from this PR, and report any success / failure on this pull request?
https://github.com/egineering-llc/collectd-fast-jmx/pull/20
