### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by tux21b** [egineering-llc/collectd-fast-jmx#18]
After a while FastJMX crashes with the following null pointer exception:

    Jul 10, 2015 9:57:45 AM org.collectd.Connection close
    WARNING: Exception closing JMXConnection: error during JRMP connection establishment; nested exception is:
            java.net.SocketTimeoutException: Read timed out
    Jul 10, 2015 9:57:50 AM org.collectd.SelfTuningCollectionExecutor push
    WARNING: Failed to collect 13 of 13 samples within read interval with 1 threads.
    Jul 10, 2015 9:57:50 AM org.collectd.Connection$ReconnectTask run
    SEVERE: Failure to close for TTL reconnect to: service:jmx:rmi:///jndi/rmi://HOSTNAME:PORT/jmxrmi
    Jul 10, 2015 9:57:50 AM org.collectd.Connection$ReconnectTask run
    INFO: Error or TTL Expiration for service:jmx:rmi:///jndi/rmi://HOSTNAME:PORT/jmxrmi forcing reconnect..
    Exception in thread "Connect-service:jmx:rmi:///jndi/rmi://HOSTNAME:PORT/jmxrmi" java.lang.NullPointerException
            at org.collectd.Connection$ReconnectTask.run(Connection.java:202)
            at java.util.TimerThread.mainLoop(Timer.java:555)
            at java.util.TimerThread.run(Timer.java:505)

**Comment by tux21b** [comment]
To be precise, FastJMX doesn't really crash, but it does not process any data either after this message.

**Comment by bvarner** [comment]
How exactly did you managed to produce that error?

It looks like you've got your hostname / port set to literally "HOSTNAME" and "PORT"?

**Comment by bvarner** [comment]
Issue closed, since it's been a few months, and the suspect configuration hasn't been disproven.
