### ISSUE TITLE
Random silent socket failures with two localhost <Connection> definitions

### ISSUE THREAD

**Issue by davidc-donorschoose** [egineering-llc/collectd-fast-jmx#22]
GENERAL DESCRIPTION: 
When I have two \<Connection\> definitions, they can silently fail, both at the same time, at random times. All of my \<Connection\> definitions are for JVM processes running on the localhost, obviously with different JMX ports. I am using the write_graphite plugin to output my metrics to a graphite running on a different server. I also have a number of input plugins other than FastJMX, but I doubt they are involved in the problem. I can run this same collectd configuration with GenericJMX without any problems.

====================
REPRO INSTRUCTIONS: 
I found two ways to repro this problem:

(1) I first noticed the problem when I had two \<Connection\> sections, and was testing whether the \<Connection\> would re-establish if I killed it's JVM and restarted it. Yes, *that* \<Connection\> was closed down and recreated as expected. However, the *other* \<Connection\> simply stopped reporting -- nothing in the /var/log/messages and nothing in my graphite. This was happening consistently, and is what I mean by "silently fail". 

(2) Then I tried a longevity test, bringing up the two JVM processes first, and letting both \<Connection\> sockets run indefinitely. Within a few hours, both sockets failed silently, apparently at the same time. This was not associated with a JVM restart, since those processes continued to run on the localhost, and I could still connect to their JMX ports using a jmxterm connection, through which I could still browse their MBeans.

====================
MORE OBSERVATIONS (and faster repro for (2) longevity testing): 
Then I instrumented my src/main/java/org/collectd/*.java code using "netstat -an" calls, allowing me to see the underlying socket connections at any point during the collectd run (basically, a "print debug" technique). I can tell the failure always happened between one FastJMX.read() call and the next Connection.ConnectTask.run() call, which are about 5 seconds apart in my configuration:
* A "netstat -an" right at the end of FastJMX.read() call shows that each \<Connection\> still has an ESTABLISHED socket.
* A "netstat -an" right at the top of Connection.ConnectTask.run() will show every socket in TIME_WAIT. Of course, it's only TIME_WAIT when the sockets failed silently -- usually there isn't a failure.

This has the appearance of being a race condition, but there is only one FastJMX thread running, so I can only speculate. I do know that when I sprinkled a dozen or so of those "netstat -an" calls in the *.java code, the failures would happen very quickly. It usually takes less than one minute after the "service collectd start" for the sockets to fail into TIME_WAIT.

====================
CODE THAT CAN REPRODUCE THE PROBLEM:
This is the instrumentation method I added to print out "netstat -an" output. My two JVM processes are serving JMX on ports 10001 and 10002:
```
import java.io.BufferedReader;
import java.io.InputStreamReader;

        private void reportNetstat(String label)
        {
          final String cmd = "netstat -an";
          try {
              // Run netstat
              Process process = Runtime.getRuntime().exec(cmd);
              process.waitFor();
              BufferedReader reader =
                   new BufferedReader(new InputStreamReader(process.getInputStream()));
              String line = "";
              while ((line = reader.readLine())!= null) {
                if (line.contains(":10001      ESTABLISHED")
                 || line.contains(":10002      ESTABLISHED")
                 || line.contains(":10001      TIME_WAIT")
                 || line.contains(":10002      TIME_WAIT")
                ) {
                  logger.info("NETSTAT " + label + ": " + line);
                }
              }
          } catch (Exception e) {
              e.printStackTrace(System.err);
          }
        }
```
-----------------------------------
This is a trivial java program that can be used for the JVM processes for the <Connection> to watch. Obviously, anything will do, but if you don't have something handy, use this (I cribbed it from somewhere, with some modifications):
```
cd /tmp/mina

cat >>TCPServer.java <<EOF
import java.io.*;
import java.net.*;
class TCPServer {
    public static void main(String argv[]) throws Exception       {
         String clientSentence;
         String capitalizedSentence;
         int portNumber = Integer.valueOf(argv[0]);
         ServerSocket welcomeSocket = new ServerSocket(portNumber);
         while(true)          {
             Socket connectionSocket = welcomeSocket.accept();
            BufferedReader inFromClient =                new BufferedReader(new InputStreamReader(connectionSocket.getInputStream()));
            DataOutputStream outToClient = new DataOutputStream(connectionSocket.getOutputStream());
            clientSentence = inFromClient.readLine();
            System.out.println("Received: " + clientSentence);
            capitalizedSentence = clientSentence.toUpperCase() + '\n';
            outToClient.writeBytes(capitalizedSentence);
         }
       }
 }
EOF

javac *java

java -Dcom.sun.management.jmxremote.port=10001 \
     -Dcom.sun.management.jmxremote.local.only=false \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Dcom.sun.management.jmxremote.ssl=false \
     -classpath . TCPServer 20001
```
That JVM listens for JMX connections on 10001 and TELNET on 20001. I run two of those in different terminal shells sessions, using JMX ports 10001 and 10002.

**Comment by zsuzhengdu** [comment]
+1 Same issue observed.

**Comment by bvarner** [comment]
I've had the same issue -- I moved to a different client project and haven't been actively dealing with collectd for a few months (hence the slow feedback here)...

I have a feeling @zsuzhengdu may be onto something with one of his questions he just asked on a different commit. I'll do some poking around. Thanks for the reproduce instructions. i'll reply here when I'm able to duplicate.

**Comment by bvarner** [comment]
@davidc-donorschoose, based on your description, would it make sense for the issue to be occurring when one of the connections is being re-established (discovering permutations) and another one is either reading, or dealing with a disconnect? 

I believe the race exists with the collectablePermutations, a shared list of objects to read which exists in FastJMX. It looks like I properly synchronized when removing and reading, but not when _adding_ permutations.

**Comment by bvarner** [comment]
If this issue can be reproduced by someone after this commit, we'll re-open the issue. Any feedback would be appreciated.
