### ISSUE TITLE
allowing override of hostname

### ISSUE THREAD

**Issue by lusis** [egineering-llc/collectd-fast-jmx#29]
Is there a mechanism to actually allow overridding the hostname if we WANT to do so? I left the `Hostname` option in but it still used localhost.

The reason we need this is because the way SignalFX tags metrics is by overridding the hostname like so:

```
Host "hostname[hostHasService=activemq]"
```

**Comment by bvarner** [comment]
Can you provide an example of your fastjmx config?

**Comment by lusis** [comment]
I'll have to generate a new one in the AM for testing. What I *CAN* easily paste for now is the way signalfx likes to do the jmx plugins:

This is the base jmx config. I was able to easily swap this out:
https://github.com/signalfx/signalfx-collectd-configs/blob/master/managed_config/10-jmx.conf

However this is a standard connection block they use:

```
        <Connection>
            ServiceURL "service:jmx:rmi:///jndi/rmi://localhost:7099/jmxrmi"
            Host "testkafkaserver[hostHasService=kafka]"
            Collect "classes"
            Collect "garbage_collector"
            Collect "memory-heap"
            Collect "memory-nonheap"
            Collect "memory_pool"
            
            Collect "kafka-all-messages"
            Collect "kafka-all-bytes-in"
            Collect "kafka-all-bytes-out"
            Collect "kafka-log-flush"
            Collect "kafka-active-controllers"
            Collect "kafka-underreplicated-partitions"
            Collect "kafka-request-queue"
            Collect "kafka.fetch-consumer.total-time"
            Collect "kafka.fetch-follower.total-time"
            Collect "kafka.produce.total-time"
        </Connection>
```

Obviously the hostname provided is invalid. SignalFX used the additional data in the Host as a dimension. The JMX call is still made against the serviceurl. I'm not expecting you to support the bit of craziness they want to use for the hostname but ideally I'd like a mode that behaved somewhat like the original JMX plugin - jmx calls are made against the ServiceURL (or in the fasterjmx case - listeners registered) while the `Host` value is sent verbatim.

**Comment by bvarner** [comment]
Thanks. Now that I understand what you're expecting and what's going on, the next time I'm able to give this project some attention I'll take a poke at getting something you could use.

Alternately, let me invite you to fork, make some adjustments and send us a pull request! :-)

**Comment by manivannan-g** [comment]
Hi, I'm also trying to override the `Hostname`. But it's not working. I tried both `Host "host10.example.com"` and `Hostname "host10.example.com"`. Is this feature still under development ?
```
<Connection>
                Host "host10.example.com"
                ServiceURL "service:jmx:rmi:///jndi/rmi://localhost:9003/jmxrmi"
                Collect "1"
                Collect "2"
                Collect "3"
</Connection>
```

**Comment by bvarner** [comment]
For both @manivannan-g and @lusis ... 

* The documentation differs from the current code in 1.0.0, and 1.1.0-SNAPSHOT. The "host" property is not respected.

I will be correcting the documentation.

The 1.0.0 code (and 1.1.0-SNAPSHOT) _do_ try to get the hostname from a string parameter on the Connection definition as a hostname override. So perhaps you could try:

```
<Connection "testkafkaserver[hostHasService=kafka]">
</Connection>
```

Or:

```
<Connection "host10.example.com">
                ServiceURL "service:jmx:rmi:///jndi/rmi://localhost:9003/jmxrmi"
                Collect "1"
                Collect "2"
                Collect "3"
</Connection>
```

**Comment by manivannan-g** [comment]
Thanks @bvarner

**Comment by lajoie** [comment]
Adding the label in the <Connection> declaration worked for me.
