### ISSUE TITLE
jmxmp support

### ISSUE THREAD

**Issue by gallenza** [egineering-llc/collectd-fast-jmx#36]
Is it possible to connect using jmxmp instead of rmi?

My jmx.conf:

-----
     LoadPlugin java
     <Plugin "java">
     JVMARG "-Djava.class.path=/usr/share/collectd/java/collectd-api.jar:/usr/share/collectd/java/collectd-fast-jmx-1.0.0.jar:/usr/share/collectd/java/jconsole.jar:/usr/share/collectd/java/jmxremote_optional.jar"
     LoadPlugin "com.e_gineering.collectd.FastJMX"

     <Plugin "FastJMX">
     MaxThreads 256
     CollectInternal true
    LogLevel "FINE"
    ForceLoggingTo "WARNING"
    # Memory usage by memory pool.
    <MBean "memory_pool">
      ObjectName "java.lang:type=MemoryPool,*"
      InstancePrefix "memory_pool-"
      InstanceFrom "name"

      <Value "Usage">
        Type "java_memory"
        Composite true
        PluginName "JVM"
      </Value>
    </MBean>

    <Connection>
      ServiceURL "service:jmx:jmxmp://localhost:31301"
      IncludePortInHostname true
      Username "foo"
      Password "bar"
      Collect "memory_pool"
    </Connection>

Error message:

[2017-02-12 14:34:53] FastJMX Plugin: Invoking javax.management.remote.jmxmp.JMXMPConnector.connect() on Connect-service:jmx:jmxmp://localhost:31301
[2017-02-12 14:34:53] FastJMX Plugin: Could not connect to : service:jmx:jmxmp://10.32.14.31:31301 exception message: The client does not require any profile but the server mandates one

**Comment by bvarner** [comment]
Sorry for not responding sooner... did you close this out of frustration or is it working for you?

**Comment by gallenza** [comment]
I don't think it has anything to do with collectd-fast-jmx. It looks like the server needs the client connect using "SASL/PLAIN", but I can't figure out how to specify a profile.
